apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
        - name: books-service
          image: apetrovic6/books-service
          imagePullPolicy: IfNotPresent 
---
apiVersion: v1
kind: Service
metadata:
  name: books-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: books-service
  ports:
    - name: grpc-port
      protocol: TCP
      port: 443
      targetPort: 443
      
---
apiVersion: v1
kind: Service
metadata:
  name: books-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: books-service
  ports:
    - name: grpc-loadbalancer
      protocol: TCP
      port: 443
      targetPort: 443